name: "ship-reader-1"
api: "http://127.0.0.1:8080"
message_codec: "json"

log:
  filename: thalos.log
  directory: logs
  time_format: 2006-01-02_150405
  max_filesize: 200mb
  max_time: 24h

ship:
  url: "ws://127.0.0.1:8089"
  irreversible_only: false
  max_messages_in_flight: 10
  start_block_num: 4294967295
  end_block_num: 4294967295

telegram:
  id: "110201543:AAHdqTcvCH1vGWJxfSeofSAs0K5PALDsaw"
  channel: -123456789

redis:
  addr: "localhost:6379"
  pasword: ""
  db: 0
  prefix: "ship"
