name: Test

on:
  - push
  - pull_request

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.20", "1.21"]
        os: [ linux, freebsd ]
        arch: [ 386, amd64, arm, arm64 ]
    runs-on: ubuntu-latest
    name: Test (${{matrix.os}} ${{matrix.arch}} go v${{ matrix.go-version }})
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Test
      run: GOOS=${{matrix.os}} GOARCH=${{matrix.arch}} go test -v ./...

    - name: Test API
      run: cd api; GOOS=${{matrix.os}} GOARCH=${{matrix.arch}} go test -v ./...

  test-alpine:
    strategy:
      fail-fast: false
      matrix:
        tag: ["1.20-alpine3.19", "1.21-alpine3.19"]
    runs-on: ubuntu-latest
    name: Test alpine (${{ matrix.tag }})
    container:
      image: golang:${{ matrix.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: go test -v ./...

      - name: Test API
        run: cd api; go test -v ./...

